version: '3.8'

services:
  redis: 
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
  ms_write_file:
    build: ms_write_file
    ports:
    - "5000:5000"
    volumes:        
    - ./ms_write_file:/app
  ms_celery_worker:
    build: ms_celery_worker
    volumes:        
    - ./ms_celery_worker:/app
    environment:
    - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
    depends_on:
    - redis